
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:5 (project)"
    message: |
      The system is: Windows - 10.0 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:5 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: D:/cygwin/bin/clang-8.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is Clang, found in:
        E:/avg4k/Average4k/CMakeFiles/3.29.0-rc1/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:5 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-nrvxb2"
      binary: "E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-nrvxb2"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-nrvxb2'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_79004/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_79004.dir/build.make CMakeFiles/cmTC_79004.dir/build
        make.exe[1]: Entering directory `E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-nrvxb2'
        Building CXX object CMakeFiles/cmTC_79004.dir/CMakeCXXCompilerABI.cpp.obj
        make.exe[1]: *** [CMakeFiles/cmTC_79004.dir/CMakeCXXCompilerABI.cpp.obj] Error 126
        make.exe[1]: Leaving directory `E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-nrvxb2'
        make.exe: *** [cmTC_79004/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:49 (try_compile)"
      - "CMakeLists.txt:5 (project)"
    checks:
      - "Check for working CXX compiler: D:/cygwin/bin/clang-8.exe"
    directories:
      source: "E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-77jkgu"
      binary: "E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-77jkgu"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-77jkgu'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_4aa2d/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_4aa2d.dir/build.make CMakeFiles/cmTC_4aa2d.dir/build
        make.exe[1]: Entering directory `E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-77jkgu'
        Building CXX object CMakeFiles/cmTC_4aa2d.dir/testCXXCompiler.cxx.obj
        make.exe[1]: *** [CMakeFiles/cmTC_4aa2d.dir/testCXXCompiler.cxx.obj] Error 126
        make.exe[1]: Leaving directory `E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-77jkgu'
        make.exe: *** [cmTC_4aa2d/fast] Error 2
        
      exitCode: 2
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: D:/cygwin/bin/clang-8.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is Clang, found in:
        E:/avg4k/Average4k/CMakeFiles/3.29.0-rc1/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:64 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:7 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-yn9wur"
      binary: "E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-yn9wur"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-yn9wur'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_8b6f4/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_8b6f4.dir/build.make CMakeFiles/cmTC_8b6f4.dir/build
        make.exe[1]: Entering directory `E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-yn9wur'
        Building CXX object CMakeFiles/cmTC_8b6f4.dir/CMakeCXXCompilerABI.cpp.obj
        make.exe[1]: *** [CMakeFiles/cmTC_8b6f4.dir/CMakeCXXCompilerABI.cpp.obj] Error 126
        make.exe[1]: Leaving directory `E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-yn9wur'
        make.exe: *** [cmTC_8b6f4/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:49 (try_compile)"
      - "CMakeLists.txt:7 (project)"
    checks:
      - "Check for working CXX compiler: D:/cygwin/bin/clang-8.exe"
    directories:
      source: "E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-x99xwc"
      binary: "E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-x99xwc"
    cmakeVariables:
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS-NOTFOUND"
      CMAKE_CXX_FLAGS: ""
      CMAKE_CXX_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_CXX_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-x99xwc'
        
        Run Build Command(s): "C:/Program Files/CMake/bin/cmake.exe" -E env VERBOSE=1 C:/PROGRA~2/GnuWin32/bin/make.exe -f Makefile cmTC_26072/fast
        C:/PROGRA~2/GnuWin32/bin/make.exe  -f CMakeFiles/cmTC_26072.dir/build.make CMakeFiles/cmTC_26072.dir/build
        make.exe[1]: Entering directory `E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-x99xwc'
        Building CXX object CMakeFiles/cmTC_26072.dir/testCXXCompiler.cxx.obj
        make.exe[1]: *** [CMakeFiles/cmTC_26072.dir/testCXXCompiler.cxx.obj] Error 126
        make.exe[1]: Leaving directory `E:/avg4k/Average4k/CMakeFiles/CMakeScratch/TryCompile-x99xwc'
        make.exe: *** [cmTC_26072/fast] Error 2
        
      exitCode: 2
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: D:/cygwin/bin/clang-8.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is Clang, found in:
        E:/avg4k/Average4k/CMakeFiles/3.29.0-rc1/CompilerIdCXX/a.exe
      
...
